version: '3.7'

services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    command: -smallfiles

  app:
    image: hmlpcb
    ports:
      - 8080:8080
    depends_on:
      - mongo
    environment:
      - "SPRING_DATA_MONGODB_HOST=mongo"